// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"database/sql"
	"time"
)

type Url struct {
	ID             int32
	CustomAlias    string
	OriginalUrl    string
	CreatedAt      time.Time
	ExpirationDate sql.NullTime
}
