// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"database/sql"
)

type Url struct {
	ID             int32
	ShortUrl       string
	OriginalUrl    string
	CreatedAt      sql.NullTime
	ExpirationDate sql.NullTime
	CustomAlias    sql.NullString
}
