// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls.sql

package repositories

import (
	"context"
	"database/sql"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_url, original_url, expiration_date, custom_alias)
VALUES (
  $1, $2, $3, $4
)
RETURNING id, short_url, original_url, created_at, expiration_date, custom_alias
`

type CreateURLParams struct {
	ShortUrl       string
	OriginalUrl    string
	ExpirationDate sql.NullTime
	CustomAlias    sql.NullString
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.ShortUrl,
		arg.OriginalUrl,
		arg.ExpirationDate,
		arg.CustomAlias,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpirationDate,
		&i.CustomAlias,
	)
	return i, err
}
