name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > env.yaml

      - name: Build Go binary for prod
        run: CGO_ENABLED=0 GOOS=linux go build -C cmd -o url-shortener

      - name: Authorize GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build image
        run: gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/url-shortener .

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Migrate db
        run: ./scripts/migrate.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy url-shortener \
          --image=gcr.io/${{ secrets.PROJECT_ID }}/url-shortener \
          --region=asia-southeast2 \
          --platform=managed \
          --max-instances=4 \
          --env-vars-file=env.yaml \
          --allow-unauthenticated
